language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install .
    - pip install -r tests/requirements.txt
    - ./tests/setup.sh
script: nosetests --with-coverage
after_success: coveralls
